ktor:
    application:
        modules:
            - ph.dsi.srms.ApplicationKt.module
    deployment:
        port: 3011
jwt:
    # openssl rand -base64 32
    secret: "4ER/ul8xE0+djEaMTDjGBpobuHkXh2b+X4OhBIkSoeE="
    domain: "http://localhost:3001"
    audience: "srms"
    realm: "DSI SRMS"
db:
    host: "LAPTOP-14C4E4AT:AX7"
    port: "AX7"
    name: "srmsdb"
    username: "ingres"
    password: "a1a1"