ktor:
    application:
        modules:
            - ph.dsi.srms.api.ApplicationKt.module
    deployment:
        port: 8080
jwt:
    # openssl rand -base64 32
    secret: "4ER/ul8xE0+djEaMTDjGBpobuHkXh2b+X4OhBIkSoeE="
    domain: "http://localhost:8080"
    audience: "srms"
    realm: "DSI SRMS"
